openapi: 3.0.0
info:
  title: API Gestion d'Utilisateurs
  version: 1.0.0
  description: API pour la gestion des utilisateurs
paths:
  /users:
    get:
      summary: Récupère la liste des utilisateurs
      description: Retourne une liste d'utilisateurs avec les paramètres page et size
      parameters:
        - name: page
          in: query
          description: Numéro de la page à récupérer
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: size
          in: query
          description: Nombre d'utilisateurs par page
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Kevin"
                    email:
                      type: string
                      format: email
                      example: "Kevin@example.com"
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"